import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import type { ModelDeclaration } from "@versionless/core";

import { CliError } from "../errors";
import { green, bold, dim } from "../colors";
import type { DiffEntry } from "../diff/diff";
import { performCheck, type CheckResult } from "./check";
import { GLOBAL_OPTIONS, loadProject, parseFlags, str, todayUtc } from "./shared";

const HELP = `versionless generate — scaffold a change file covering the diffs
that \`versionless check\` reports as uncovered.

Usage: versionless generate [options]

Options:
  --config <path>  Path to versionless.config.ts
  --json           Machine-readable output
  -h, --help       Show this help
`;

/** The static directory prefix of a glob ("changes/**\/*.ts" → "changes"). */
export function globBaseDir(glob: string): string {
  const segments = glob.split("/");
  const static_: string[] = [];
  for (const segment of segments) {
    if (/[*?[\]{}]/.test(segment)) break;
    static_.push(segment);
  }
  // A glob like "changes/foo.ts" ends with a filename — drop it.
  const last = static_[static_.length - 1];
  if (static_.length === segments.length && last !== undefined && last.includes(".")) {
    static_.pop();
  }
  return static_.length > 0 ? static_.join("/") : "changes";
}

function buildDeclarations(entries: DiffEntry[]): {
  declarations: ModelDeclaration[];
  routesRemoved: string[];
} {
  const byModel = new Map<string, ModelDeclaration>();
  const routesRemoved: string[] = [];
  for (const entry of entries) {
    if (entry.op === "endpoint-removed") {
      if (!routesRemoved.includes(entry.endpoint)) routesRemoved.push(entry.endpoint);
      continue;
    }
    if (entry.model === undefined || entry.fieldPath === undefined) continue;
    let decl = byModel.get(entry.model);
    if (!decl) {
      decl = { model: entry.model };
      byModel.set(entry.model, decl);
    }
    const list =
      entry.op === "field-removed"
        ? (decl.removed ??= [])
        : entry.op === "field-added"
          ? (decl.added ??= [])
          : (decl.typeChanged ??= []);
    if (!list.includes(entry.fieldPath)) list.push(entry.fieldPath);
  }
  return { declarations: [...byModel.values()], routesRemoved };
}

function renderStringArray(values: string[]): string {
  return `[${values.map((v) => JSON.stringify(v)).join(", ")}]`;
}

export function renderChangeFile(result: CheckResult, opts: {
  entryImport: string;
  instanceExport: string;
  hasInstance: boolean;
}): string {
  const uncovered = result.report.uncovered.map((i) => i.entry);
  const { declarations, routesRemoved } = buildDeclarations(uncovered);

  const needsUp = uncovered.some((e) => e.requires === "up");
  const needsDown = uncovered.some((e) => e.requires === "down");

  const routes = [
    ...new Set(
      uncovered
        .filter((e) => !e.endpoint.startsWith("trpc:"))
        .map((e) => e.endpoint),
    ),
  ];
  const procedures = [
    ...new Set(
      uncovered
        .filter((e) => e.endpoint.startsWith("trpc:"))
        .map((e) => e.endpoint.slice("trpc:".length)),
    ),
  ];

  const header = [
    "/**",
    " * Generated by `versionless generate` — fill in the TODOs.",
    " *",
    " * Uncovered diffs this change must cover:",
    ...uncovered.map((e) => {
      const subject =
        e.model !== undefined && e.fieldPath !== undefined
          ? `${e.model}.${e.fieldPath}`
          : (e.fieldPath ?? e.endpoint);
      const shape =
        e.before !== undefined || e.after !== undefined
          ? ` (${e.before ?? "?"} -> ${e.after ?? "?"})`
          : "";
      return ` *   - [${e.severity}] ${e.op}: ${subject} in ${e.location} of ${e.endpoint}${shape}`;
    }),
    " */",
  ].join("\n");

  const importLine = opts.hasInstance
    ? `import { ${opts.instanceExport} as v } from ${JSON.stringify(opts.entryImport)};`
    : `// TODO: import your versionless instance:\n// import { versionless as v } from ${JSON.stringify(opts.entryImport)};\nimport { ${opts.instanceExport} as v } from ${JSON.stringify(opts.entryImport)};`;

  const specLines: string[] = [
    `  describe: "TODO: describe this change",`,
  ];
  if (routes.length > 0) specLines.push(`  routes: ${renderStringArray(routes)},`);
  if (procedures.length > 0) {
    specLines.push(`  procedures: ${renderStringArray(procedures)},`);
  }

  const onCalls: string[] = declarations.map((decl) => {
    const parts: string[] = [];
    if (decl.removed) parts.push(`removed: ${renderStringArray(decl.removed)}`);
    if (decl.added) parts.push(`added: ${renderStringArray(decl.added)}`);
    if (decl.typeChanged) {
      parts.push(`typeChanged: ${renderStringArray(decl.typeChanged)}`);
    }
    return `.on(${JSON.stringify(decl.model)}, { ${parts.join(", ")} })`;
  });
  if (routesRemoved.length > 0) {
    onCalls.push(
      `.on("TODO_Model" /* the model whose routes went away */, { routesRemoved: ${renderStringArray(routesRemoved)} })`,
    );
  }
  if (onCalls.length > 0) {
    specLines.push(`  schema: (s) => {`);
    specLines.push(`    s${onCalls.map((c) => `\n      ${c}`).join("")};`);
    specLines.push(`  },`);
  }
  if (needsUp) {
    specLines.push(
      `  request: {`,
      `    up: (body) => {`,
      `      // TODO: convert the OLD request shape into the current one`,
      `      return body;`,
      `    },`,
      `  },`,
    );
  }
  if (needsDown) {
    specLines.push(
      `  response: {`,
      `    down: (body) => {`,
      `      // TODO: convert the CURRENT response shape back into the old one`,
      `      return body;`,
      `    },`,
      `  },`,
    );
  }

  return [
    header,
    importLine,
    "",
    `export default v.change(${JSON.stringify(result.headVersion)}, {`,
    specLines.join("\n"),
    `});`,
    "",
  ].join("\n");
}

/** Pick a non-clobbering path: <v>-generated.ts, <v>-generated-2.ts, ... */
function freshPath(dir: string, version: string): string {
  const base = join(dir, `${version}-generated.ts`);
  if (!existsSync(base)) return base;
  for (let i = 2; ; i++) {
    const candidate = join(dir, `${version}-generated-${i}.ts`);
    if (!existsSync(candidate)) return candidate;
  }
}

export async function runGenerate(
  argv: string[],
  cwd = process.cwd(),
): Promise<number> {
  const { values } = parseFlags(argv, { ...GLOBAL_OPTIONS });
  if (values["help"] === true) {
    process.stdout.write(HELP);
    return 0;
  }

  const configPath = str(values["config"]);
  // performCheck loads the project itself; re-load config only for paths.
  const { config, entry } = await loadProject(cwd, configPath);
  const result = await performCheck(cwd, configPath);

  if (result.report.uncovered.length === 0) {
    console.log(`${green("✓")} nothing to generate — no uncovered breaking changes`);
    return 0;
  }

  // A breaking change ships in a NEW version: coverage only considers changes
  // strictly newer than the last snapshot, and core refuses change versions
  // newer than `current` — so a stub stamped at an already-snapshotted head
  // could never cover anything.
  if (result.headVersion <= result.snapshotVersion) {
    throw new CliError(
      `head version ${result.headVersion} already has a committed snapshot — ` +
        `a breaking change needs a new version.\n` +
        `Bump \`current\` on your versionless instance (e.g. to ${todayUtc()}), ` +
        `then re-run \`versionless generate\`.`,
      2,
    );
  }

  const changesDir = join(config.rootDir, globBaseDir(config.changesGlob));
  mkdirSync(changesDir, { recursive: true });
  const path = freshPath(changesDir, result.headVersion);

  let entryImport = relative(dirname(path), config.entry).replace(/\.ts$/, "");
  if (!entryImport.startsWith(".")) entryImport = `./${entryImport}`;

  const content = renderChangeFile(result, {
    entryImport,
    instanceExport: config.instanceExport,
    hasInstance: entry.instance !== null,
  });
  writeFileSync(path, content);

  if (values["json"] === true) {
    console.log(
      JSON.stringify(
        { path, uncovered: result.report.uncovered.length },
        null,
        2,
      ),
    );
  } else {
    console.log(`${green("✓")} scaffolded ${bold(path)}`);
    console.log(dim("next steps:"));
    console.log(dim("  1. fill in describe + the TODO transforms"));
    console.log(dim("  2. re-run `versionless check` until it passes"));
    console.log(dim("  3. run your test suite"));
  }
  return 0;
}
