/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as UsersRouteImport } from './routes/users'
import { Route as OrgsIdRouteImport } from './routes/orgs.$id'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as UsersIdRouteImport } from './routes/users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIdRoute = OrgsIdRouteImport.update({
  id: '/orgs/$id',
  path: '/orgs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams': typeof TeamsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/orgs/$id': typeof OrgsIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/teams/$id': typeof TeamsIdRoute
  '/users/$id': typeof UsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams': typeof TeamsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/orgs/$id': typeof OrgsIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/teams/$id': typeof TeamsIdRoute
  '/users/$id': typeof UsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams': typeof TeamsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/orgs/$id': typeof OrgsIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/teams/$id': typeof TeamsIdRoute
  '/users/$id': typeof UsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams'
    | '/users'
    | '/orgs/$id'
    | '/rpc/$'
    | '/teams/$id'
    | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teams'
    | '/users'
    | '/orgs/$id'
    | '/rpc/$'
    | '/teams/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/'
    | '/teams'
    | '/users'
    | '/orgs/$id'
    | '/rpc/$'
    | '/teams/$id'
    | '/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
  OrgsIdRoute: typeof OrgsIdRoute
  RpcSplatRoute: typeof RpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$id': {
      id: '/orgs/$id'
      path: '/orgs/$id'
      fullPath: '/orgs/$id'
      preLoaderRoute: typeof OrgsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
  }
}

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsRoute: TeamsRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
  OrgsIdRoute: OrgsIdRoute,
  RpcSplatRoute: RpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
